// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicMsFigmaImport,
  DefaultMsFigmaImportProps
} from "./plasmic/copy_of_ee_report/PlasmicMsFigmaImport";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface MsFigmaImportProps extends Omit<DefaultMsFigmaImportProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultMsFigmaImportProps altogether and have
// total control over the props for your component.
export interface MsFigmaImportProps extends DefaultMsFigmaImportProps {}

function MsFigmaImport_(
  props: MsFigmaImportProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicMsFigmaImport to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicMsFigmaImport are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all MsFigmaImportProps here, but feel free
  // to do whatever works for you.

  return <PlasmicMsFigmaImport root={{ ref }} {...props} />;
}

const MsFigmaImport = React.forwardRef(MsFigmaImport_);
export default MsFigmaImport;
