// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ouJBE5YY9cRiEJb3g9pqrR
// Component: uHDoaN6cxRqG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ouJBE5YY9cRiEJb3g9pqrR/projectcss
import sty from "./PlasmicMsFigmaImport.module.css"; // plasmic-import: uHDoaN6cxRqG/css

import DividerIcon from "./icons/PlasmicIcon__Divider"; // plasmic-import: TQquHmjl-OWs/icon

createPlasmicElementProxy;

export type PlasmicMsFigmaImport__VariantMembers = {};
export type PlasmicMsFigmaImport__VariantsArgs = {};
type VariantPropType = keyof PlasmicMsFigmaImport__VariantsArgs;
export const PlasmicMsFigmaImport__VariantProps = new Array<VariantPropType>();

export type PlasmicMsFigmaImport__ArgsType = {
  verticalBarGraph2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMsFigmaImport__ArgsType;
export const PlasmicMsFigmaImport__ArgProps = new Array<ArgPropType>(
  "verticalBarGraph2"
);

export type PlasmicMsFigmaImport__OverridesType = {
  root?: Flex__<"div">;
  thisWeekAtAGlance?: Flex__<"div">;
  section?: Flex__<"div">;
  header?: Flex__<"div">;
  _100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek?: Flex__<"div">;
  graph?: Flex__<"div">;
  verticalBarGraph?: Flex__<"div">;
  tabs?: Flex__<"div">;
  header3?: Flex__<"div">;
  header2?: Flex__<"div">;
  content?: Flex__<"div">;
  tabs2?: Flex__<"div">;
  arrowsDefault?: Flex__<"div">;
  cauliflowerCard?: Flex__<"div">;
  alertDomainShutoff?: Flex__<"div">;
  badge?: Flex__<"div">;
  blurb?: Flex__<"div">;
  spacer?: Flex__<"div">;
  newItem?: Flex__<"div">;
  card?: Flex__<"div">;
  mainData?: Flex__<"div">;
  _14?: Flex__<"div">;
  students?: Flex__<"div">;
  earlyAccessMyPath?: Flex__<"div">;
  card2?: Flex__<"div">;
  alertDomainShutoff2?: Flex__<"div">;
  badge2?: Flex__<"div">;
  blurb2?: Flex__<"div">;
  spacer2?: Flex__<"div">;
  newItem2?: Flex__<"div">;
  card3?: Flex__<"div">;
  mainData2?: Flex__<"div">;
  earlyAccessMyPath2?: Flex__<"div">;
  arrow?: Flex__<"div">;
  card4?: Flex__<"div">;
  alertWarningOrange?: Flex__<"div">;
  badge3?: Flex__<"div">;
  blurb3?: Flex__<"div">;
  spacer3?: Flex__<"div">;
  newItem3?: Flex__<"div">;
  card5?: Flex__<"div">;
  mainData3?: Flex__<"div">;
  _15?: Flex__<"div">;
  earlyAccessMyPath3?: Flex__<"div">;
  arrow2?: Flex__<"div">;
};

export interface DefaultMsFigmaImportProps {
  verticalBarGraph2?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMsFigmaImport__RenderFunc(props: {
  variants: PlasmicMsFigmaImport__VariantsArgs;
  args: PlasmicMsFigmaImport__ArgsType;
  overrides: PlasmicMsFigmaImport__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"thisWeekAtAGlance"}
        data-plasmic-override={overrides.thisWeekAtAGlance}
        className={classNames(projectcss.all, sty.thisWeekAtAGlance)}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"section"}
          data-plasmic-override={overrides.section}
          hasGap={true}
          className={classNames(projectcss.all, sty.section)}
        >
          <Stack__
            as={"div"}
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            hasGap={true}
            className={classNames(projectcss.all, sty.header)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___481L
              )}
            >
              {"Lesson Time-on-Task This Week"}
            </div>
            <div
              data-plasmic-name={
                "_100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek"
              }
              data-plasmic-override={
                overrides._100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek
              }
              className={classNames(
                projectcss.all,
                sty._100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek
              )}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fmjFr
                )}
              >
                {
                  "100% of students (57 students out of 57 total) used Personalized Instruction lessons this week."
                }
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"graph"}
            data-plasmic-override={overrides.graph}
            hasGap={true}
            className={classNames(projectcss.all, sty.graph)}
          >
            <div
              data-plasmic-name={"verticalBarGraph"}
              data-plasmic-override={overrides.verticalBarGraph}
              className={classNames(projectcss.all, sty.verticalBarGraph)}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <React.Fragment>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ga5A4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ue1Fz
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__w6Cg
                          )}
                        >
                          {"Students"}
                        </div>
                      </div>
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__aJcf9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qKo5T
                        )}
                      >
                        {"1"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__eTgx9
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nwdJc
                        )}
                      >
                        {"1-9 min"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__ymOec)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4UPbq
                        )}
                      >
                        {"20"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dfgDa
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oJelH
                        )}
                      >
                        {"10-29 min"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__y43Xh)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__egwa5
                        )}
                      >
                        {"30"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__m66Re
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tNlK
                        )}
                      >
                        {"30-49 min"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__rASf)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dsn8G
                        )}
                      >
                        {"6"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jm66Q
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jQwq
                        )}
                      >
                        {"50+ min"}
                      </div>
                    </Stack__>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__za1F2)}
                    >
                      <DividerIcon
                        className={classNames(projectcss.all, sty.svg__b1Urm)}
                        role={"img"}
                      />
                    </div>
                  </React.Fragment>
                ),
                value: args.verticalBarGraph2
              })}
            </div>
          </Stack__>
        </Stack__>
      </div>
      <Stack__
        as={"div"}
        data-plasmic-name={"tabs"}
        data-plasmic-override={overrides.tabs}
        hasGap={true}
        className={classNames(projectcss.all, sty.tabs)}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"header3"}
          data-plasmic-override={overrides.header3}
          hasGap={true}
          className={classNames(projectcss.all, sty.header3)}
        >
          <Stack__
            as={"div"}
            data-plasmic-name={"header2"}
            data-plasmic-override={overrides.header2}
            hasGap={true}
            className={classNames(projectcss.all, sty.header2)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__og9PC
              )}
            >
              {"My Path Placement"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lEsfW
              )}
            >
              {
                "Of the 57 students using, 14 of them are in i-Ready Pro and 43 of them are in i-Ready."
              }
            </div>
          </Stack__>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__bLGuH
            )}
          >
            {"Select tab to view lesson results:"}
          </div>
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"content"}
          data-plasmic-override={overrides.content}
          hasGap={true}
          className={classNames(projectcss.all, sty.content)}
        >
          <div
            data-plasmic-name={"tabs2"}
            data-plasmic-override={overrides.tabs2}
            className={classNames(projectcss.all, sty.tabs2)}
          >
            <div
              data-plasmic-name={"arrowsDefault"}
              data-plasmic-override={overrides.arrowsDefault}
              className={classNames(projectcss.all, sty.arrowsDefault)}
            >
              <div
                data-plasmic-name={"cauliflowerCard"}
                data-plasmic-override={overrides.cauliflowerCard}
                className={classNames(projectcss.all, sty.cauliflowerCard)}
              >
                {false ? (
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"alertDomainShutoff"}
                    data-plasmic-override={overrides.alertDomainShutoff}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.alertDomainShutoff
                    )}
                  >
                    <div
                      data-plasmic-name={"badge"}
                      data-plasmic-override={overrides.badge}
                      className={classNames(projectcss.all, sty.badge)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fry1I
                        )}
                      >
                        {"2"}
                      </div>
                    </div>
                  </Stack__>
                ) : null}
                <div
                  data-plasmic-name={"blurb"}
                  data-plasmic-override={overrides.blurb}
                  className={classNames(projectcss.all, sty.blurb)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"spacer"}
                    data-plasmic-override={overrides.spacer}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.spacer)}
                  >
                    {false ? (
                      <div
                        data-plasmic-name={"newItem"}
                        data-plasmic-override={overrides.newItem}
                        className={classNames(projectcss.all, sty.newItem)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kgTzn
                          )}
                        >
                          {"Early Access"}
                        </div>
                      </div>
                    ) : null}
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"card"}
                  data-plasmic-override={overrides.card}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.card)}
                >
                  <div
                    data-plasmic-name={"mainData"}
                    data-plasmic-override={overrides.mainData}
                    className={classNames(projectcss.all, sty.mainData)}
                  >
                    <div
                      data-plasmic-name={"_14"}
                      data-plasmic-override={overrides._14}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty._14
                      )}
                    >
                      {"57"}
                    </div>
                    <div
                      data-plasmic-name={"students"}
                      data-plasmic-override={overrides.students}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.students
                      )}
                    >
                      {" "}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"earlyAccessMyPath"}
                    data-plasmic-override={overrides.earlyAccessMyPath}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.earlyAccessMyPath
                    )}
                  >
                    {"Total Students"}
                  </div>
                </Stack__>
              </div>
              <div
                data-plasmic-name={"card2"}
                data-plasmic-override={overrides.card2}
                className={classNames(projectcss.all, sty.card2)}
              >
                {false ? (
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"alertDomainShutoff2"}
                    data-plasmic-override={overrides.alertDomainShutoff2}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.alertDomainShutoff2
                    )}
                  >
                    <div
                      data-plasmic-name={"badge2"}
                      data-plasmic-override={overrides.badge2}
                      className={classNames(projectcss.all, sty.badge2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__k8Vqo
                        )}
                      >
                        {"2"}
                      </div>
                    </div>
                  </Stack__>
                ) : null}
                <div
                  data-plasmic-name={"blurb2"}
                  data-plasmic-override={overrides.blurb2}
                  className={classNames(projectcss.all, sty.blurb2)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"spacer2"}
                    data-plasmic-override={overrides.spacer2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.spacer2)}
                  >
                    <div
                      data-plasmic-name={"newItem2"}
                      data-plasmic-override={overrides.newItem2}
                      className={classNames(projectcss.all, sty.newItem2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vuzvy
                        )}
                      >
                        {"Early Access"}
                      </div>
                    </div>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"card3"}
                  data-plasmic-override={overrides.card3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.card3)}
                >
                  <div
                    data-plasmic-name={"mainData2"}
                    data-plasmic-override={overrides.mainData2}
                    className={classNames(projectcss.all, sty.mainData2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8KBhj
                      )}
                    >
                      {"14"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lezSp
                      )}
                    >
                      {"Students"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"earlyAccessMyPath2"}
                    data-plasmic-override={overrides.earlyAccessMyPath2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.earlyAccessMyPath2
                    )}
                  >
                    {"i-Ready Pro"}
                  </div>
                </Stack__>
                <div
                  data-plasmic-name={"arrow"}
                  data-plasmic-override={overrides.arrow}
                  className={classNames(projectcss.all, sty.arrow)}
                />
              </div>
              <div
                data-plasmic-name={"card4"}
                data-plasmic-override={overrides.card4}
                className={classNames(projectcss.all, sty.card4)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"alertWarningOrange"}
                    data-plasmic-override={overrides.alertWarningOrange}
                    className={classNames(
                      projectcss.all,
                      sty.alertWarningOrange
                    )}
                  >
                    <div
                      data-plasmic-name={"badge3"}
                      data-plasmic-override={overrides.badge3}
                      className={classNames(projectcss.all, sty.badge3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nIPwP
                        )}
                      >
                        {"2"}
                      </div>
                    </div>
                  </div>
                ) : null}
                <div
                  data-plasmic-name={"blurb3"}
                  data-plasmic-override={overrides.blurb3}
                  className={classNames(projectcss.all, sty.blurb3)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"spacer3"}
                    data-plasmic-override={overrides.spacer3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.spacer3)}
                  >
                    {false ? (
                      <div
                        data-plasmic-name={"newItem3"}
                        data-plasmic-override={overrides.newItem3}
                        className={classNames(projectcss.all, sty.newItem3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___5G1Gs
                          )}
                        >
                          {"Early Access"}
                        </div>
                      </div>
                    ) : null}
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"card5"}
                  data-plasmic-override={overrides.card5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.card5)}
                >
                  <div
                    data-plasmic-name={"mainData3"}
                    data-plasmic-override={overrides.mainData3}
                    className={classNames(projectcss.all, sty.mainData3)}
                  >
                    <div
                      data-plasmic-name={"_15"}
                      data-plasmic-override={overrides._15}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty._15
                      )}
                    >
                      {"43"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eoho7
                      )}
                    >
                      {"Students"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"earlyAccessMyPath3"}
                    data-plasmic-override={overrides.earlyAccessMyPath3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.earlyAccessMyPath3
                    )}
                  >
                    {"i-Ready"}
                  </div>
                </Stack__>
                <div
                  data-plasmic-name={"arrow2"}
                  data-plasmic-override={overrides.arrow2}
                  className={classNames(projectcss.all, sty.arrow2)}
                />
              </div>
            </div>
          </div>
        </Stack__>
      </Stack__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "thisWeekAtAGlance",
    "section",
    "header",
    "_100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek",
    "graph",
    "verticalBarGraph",
    "tabs",
    "header3",
    "header2",
    "content",
    "tabs2",
    "arrowsDefault",
    "cauliflowerCard",
    "alertDomainShutoff",
    "badge",
    "blurb",
    "spacer",
    "newItem",
    "card",
    "mainData",
    "_14",
    "students",
    "earlyAccessMyPath",
    "card2",
    "alertDomainShutoff2",
    "badge2",
    "blurb2",
    "spacer2",
    "newItem2",
    "card3",
    "mainData2",
    "earlyAccessMyPath2",
    "arrow",
    "card4",
    "alertWarningOrange",
    "badge3",
    "blurb3",
    "spacer3",
    "newItem3",
    "card5",
    "mainData3",
    "_15",
    "earlyAccessMyPath3",
    "arrow2"
  ],
  thisWeekAtAGlance: [
    "thisWeekAtAGlance",
    "section",
    "header",
    "_100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek",
    "graph",
    "verticalBarGraph"
  ],
  section: [
    "section",
    "header",
    "_100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek",
    "graph",
    "verticalBarGraph"
  ],
  header: [
    "header",
    "_100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek"
  ],
  _100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek:
    [
      "_100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek"
    ],
  graph: ["graph", "verticalBarGraph"],
  verticalBarGraph: ["verticalBarGraph"],
  tabs: [
    "tabs",
    "header3",
    "header2",
    "content",
    "tabs2",
    "arrowsDefault",
    "cauliflowerCard",
    "alertDomainShutoff",
    "badge",
    "blurb",
    "spacer",
    "newItem",
    "card",
    "mainData",
    "_14",
    "students",
    "earlyAccessMyPath",
    "card2",
    "alertDomainShutoff2",
    "badge2",
    "blurb2",
    "spacer2",
    "newItem2",
    "card3",
    "mainData2",
    "earlyAccessMyPath2",
    "arrow",
    "card4",
    "alertWarningOrange",
    "badge3",
    "blurb3",
    "spacer3",
    "newItem3",
    "card5",
    "mainData3",
    "_15",
    "earlyAccessMyPath3",
    "arrow2"
  ],
  header3: ["header3", "header2"],
  header2: ["header2"],
  content: [
    "content",
    "tabs2",
    "arrowsDefault",
    "cauliflowerCard",
    "alertDomainShutoff",
    "badge",
    "blurb",
    "spacer",
    "newItem",
    "card",
    "mainData",
    "_14",
    "students",
    "earlyAccessMyPath",
    "card2",
    "alertDomainShutoff2",
    "badge2",
    "blurb2",
    "spacer2",
    "newItem2",
    "card3",
    "mainData2",
    "earlyAccessMyPath2",
    "arrow",
    "card4",
    "alertWarningOrange",
    "badge3",
    "blurb3",
    "spacer3",
    "newItem3",
    "card5",
    "mainData3",
    "_15",
    "earlyAccessMyPath3",
    "arrow2"
  ],
  tabs2: [
    "tabs2",
    "arrowsDefault",
    "cauliflowerCard",
    "alertDomainShutoff",
    "badge",
    "blurb",
    "spacer",
    "newItem",
    "card",
    "mainData",
    "_14",
    "students",
    "earlyAccessMyPath",
    "card2",
    "alertDomainShutoff2",
    "badge2",
    "blurb2",
    "spacer2",
    "newItem2",
    "card3",
    "mainData2",
    "earlyAccessMyPath2",
    "arrow",
    "card4",
    "alertWarningOrange",
    "badge3",
    "blurb3",
    "spacer3",
    "newItem3",
    "card5",
    "mainData3",
    "_15",
    "earlyAccessMyPath3",
    "arrow2"
  ],
  arrowsDefault: [
    "arrowsDefault",
    "cauliflowerCard",
    "alertDomainShutoff",
    "badge",
    "blurb",
    "spacer",
    "newItem",
    "card",
    "mainData",
    "_14",
    "students",
    "earlyAccessMyPath",
    "card2",
    "alertDomainShutoff2",
    "badge2",
    "blurb2",
    "spacer2",
    "newItem2",
    "card3",
    "mainData2",
    "earlyAccessMyPath2",
    "arrow",
    "card4",
    "alertWarningOrange",
    "badge3",
    "blurb3",
    "spacer3",
    "newItem3",
    "card5",
    "mainData3",
    "_15",
    "earlyAccessMyPath3",
    "arrow2"
  ],
  cauliflowerCard: [
    "cauliflowerCard",
    "alertDomainShutoff",
    "badge",
    "blurb",
    "spacer",
    "newItem",
    "card",
    "mainData",
    "_14",
    "students",
    "earlyAccessMyPath"
  ],
  alertDomainShutoff: ["alertDomainShutoff", "badge"],
  badge: ["badge"],
  blurb: ["blurb", "spacer", "newItem"],
  spacer: ["spacer", "newItem"],
  newItem: ["newItem"],
  card: ["card", "mainData", "_14", "students", "earlyAccessMyPath"],
  mainData: ["mainData", "_14", "students"],
  _14: ["_14"],
  students: ["students"],
  earlyAccessMyPath: ["earlyAccessMyPath"],
  card2: [
    "card2",
    "alertDomainShutoff2",
    "badge2",
    "blurb2",
    "spacer2",
    "newItem2",
    "card3",
    "mainData2",
    "earlyAccessMyPath2",
    "arrow"
  ],
  alertDomainShutoff2: ["alertDomainShutoff2", "badge2"],
  badge2: ["badge2"],
  blurb2: ["blurb2", "spacer2", "newItem2"],
  spacer2: ["spacer2", "newItem2"],
  newItem2: ["newItem2"],
  card3: ["card3", "mainData2", "earlyAccessMyPath2"],
  mainData2: ["mainData2"],
  earlyAccessMyPath2: ["earlyAccessMyPath2"],
  arrow: ["arrow"],
  card4: [
    "card4",
    "alertWarningOrange",
    "badge3",
    "blurb3",
    "spacer3",
    "newItem3",
    "card5",
    "mainData3",
    "_15",
    "earlyAccessMyPath3",
    "arrow2"
  ],
  alertWarningOrange: ["alertWarningOrange", "badge3"],
  badge3: ["badge3"],
  blurb3: ["blurb3", "spacer3", "newItem3"],
  spacer3: ["spacer3", "newItem3"],
  newItem3: ["newItem3"],
  card5: ["card5", "mainData3", "_15", "earlyAccessMyPath3"],
  mainData3: ["mainData3", "_15"],
  _15: ["_15"],
  earlyAccessMyPath3: ["earlyAccessMyPath3"],
  arrow2: ["arrow2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  thisWeekAtAGlance: "div";
  section: "div";
  header: "div";
  _100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek: "div";
  graph: "div";
  verticalBarGraph: "div";
  tabs: "div";
  header3: "div";
  header2: "div";
  content: "div";
  tabs2: "div";
  arrowsDefault: "div";
  cauliflowerCard: "div";
  alertDomainShutoff: "div";
  badge: "div";
  blurb: "div";
  spacer: "div";
  newItem: "div";
  card: "div";
  mainData: "div";
  _14: "div";
  students: "div";
  earlyAccessMyPath: "div";
  card2: "div";
  alertDomainShutoff2: "div";
  badge2: "div";
  blurb2: "div";
  spacer2: "div";
  newItem2: "div";
  card3: "div";
  mainData2: "div";
  earlyAccessMyPath2: "div";
  arrow: "div";
  card4: "div";
  alertWarningOrange: "div";
  badge3: "div";
  blurb3: "div";
  spacer3: "div";
  newItem3: "div";
  card5: "div";
  mainData3: "div";
  _15: "div";
  earlyAccessMyPath3: "div";
  arrow2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMsFigmaImport__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMsFigmaImport__VariantsArgs;
    args?: PlasmicMsFigmaImport__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMsFigmaImport__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicMsFigmaImport__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMsFigmaImport__ArgProps,
          internalVariantPropNames: PlasmicMsFigmaImport__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMsFigmaImport__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMsFigmaImport";
  } else {
    func.displayName = `PlasmicMsFigmaImport.${nodeName}`;
  }
  return func;
}

export const PlasmicMsFigmaImport = Object.assign(
  // Top-level PlasmicMsFigmaImport renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    thisWeekAtAGlance: makeNodeComponent("thisWeekAtAGlance"),
    section: makeNodeComponent("section"),
    header: makeNodeComponent("header"),
    _100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek:
      makeNodeComponent(
        "_100OfStudents57StudentsOutOf57TotalUsedPersonalizedInstructionLessonsThisWeek"
      ),
    graph: makeNodeComponent("graph"),
    verticalBarGraph: makeNodeComponent("verticalBarGraph"),
    tabs: makeNodeComponent("tabs"),
    header3: makeNodeComponent("header3"),
    header2: makeNodeComponent("header2"),
    content: makeNodeComponent("content"),
    tabs2: makeNodeComponent("tabs2"),
    arrowsDefault: makeNodeComponent("arrowsDefault"),
    cauliflowerCard: makeNodeComponent("cauliflowerCard"),
    alertDomainShutoff: makeNodeComponent("alertDomainShutoff"),
    badge: makeNodeComponent("badge"),
    blurb: makeNodeComponent("blurb"),
    spacer: makeNodeComponent("spacer"),
    newItem: makeNodeComponent("newItem"),
    card: makeNodeComponent("card"),
    mainData: makeNodeComponent("mainData"),
    _14: makeNodeComponent("_14"),
    students: makeNodeComponent("students"),
    earlyAccessMyPath: makeNodeComponent("earlyAccessMyPath"),
    card2: makeNodeComponent("card2"),
    alertDomainShutoff2: makeNodeComponent("alertDomainShutoff2"),
    badge2: makeNodeComponent("badge2"),
    blurb2: makeNodeComponent("blurb2"),
    spacer2: makeNodeComponent("spacer2"),
    newItem2: makeNodeComponent("newItem2"),
    card3: makeNodeComponent("card3"),
    mainData2: makeNodeComponent("mainData2"),
    earlyAccessMyPath2: makeNodeComponent("earlyAccessMyPath2"),
    arrow: makeNodeComponent("arrow"),
    card4: makeNodeComponent("card4"),
    alertWarningOrange: makeNodeComponent("alertWarningOrange"),
    badge3: makeNodeComponent("badge3"),
    blurb3: makeNodeComponent("blurb3"),
    spacer3: makeNodeComponent("spacer3"),
    newItem3: makeNodeComponent("newItem3"),
    card5: makeNodeComponent("card5"),
    mainData3: makeNodeComponent("mainData3"),
    _15: makeNodeComponent("_15"),
    earlyAccessMyPath3: makeNodeComponent("earlyAccessMyPath3"),
    arrow2: makeNodeComponent("arrow2"),

    // Metadata about props expected for PlasmicMsFigmaImport
    internalVariantProps: PlasmicMsFigmaImport__VariantProps,
    internalArgProps: PlasmicMsFigmaImport__ArgProps
  }
);

export default PlasmicMsFigmaImport;
/* prettier-ignore-end */
