// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ouJBE5YY9cRiEJb3g9pqrR
// Component: _CpF-W7buP_c

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import AdminDiagResultsReportContent from "../../AdminDiagResultsReportContent"; // plasmic-import: FBn8CS733jVG/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ouJBE5YY9cRiEJb3g9pqrR/projectcss
import sty from "./PlasmicAdminDiagResults.module.css"; // plasmic-import: _CpF-W7buP_c/css

createPlasmicElementProxy;

export type PlasmicAdminDiagResults__VariantMembers = {};
export type PlasmicAdminDiagResults__VariantsArgs = {};
type VariantPropType = keyof PlasmicAdminDiagResults__VariantsArgs;
export const PlasmicAdminDiagResults__VariantProps =
  new Array<VariantPropType>();

export type PlasmicAdminDiagResults__ArgsType = {};
type ArgPropType = keyof PlasmicAdminDiagResults__ArgsType;
export const PlasmicAdminDiagResults__ArgProps = new Array<ArgPropType>();

export type PlasmicAdminDiagResults__OverridesType = {
  root?: Flex__<"div">;
  adminDiagResultsReportContent?: Flex__<typeof AdminDiagResultsReportContent>;
};

export interface DefaultAdminDiagResultsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAdminDiagResults__RenderFunc(props: {
  variants: PlasmicAdminDiagResults__VariantsArgs;
  args: PlasmicAdminDiagResults__ArgsType;
  overrides: PlasmicAdminDiagResults__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />

        <link
          rel="canonical"
          href={PlasmicAdminDiagResults.pageMetadata.canonical}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <AdminDiagResultsReportContent
            data-plasmic-name={"adminDiagResultsReportContent"}
            data-plasmic-override={overrides.adminDiagResultsReportContent}
            className={classNames(
              "__wab_instance",
              sty.adminDiagResultsReportContent
            )}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "adminDiagResultsReportContent"],
  adminDiagResultsReportContent: ["adminDiagResultsReportContent"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  adminDiagResultsReportContent: typeof AdminDiagResultsReportContent;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAdminDiagResults__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAdminDiagResults__VariantsArgs;
    args?: PlasmicAdminDiagResults__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAdminDiagResults__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAdminDiagResults__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAdminDiagResults__ArgProps,
          internalVariantPropNames: PlasmicAdminDiagResults__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAdminDiagResults__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAdminDiagResults";
  } else {
    func.displayName = `PlasmicAdminDiagResults.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "ouJBE5YY9cRiEJb3g9pqrR"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicAdminDiagResults = Object.assign(
  // Top-level PlasmicAdminDiagResults renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    adminDiagResultsReportContent: makeNodeComponent(
      "adminDiagResultsReportContent"
    ),

    // Metadata about props expected for PlasmicAdminDiagResults
    internalVariantProps: PlasmicAdminDiagResults__VariantProps,
    internalArgProps: PlasmicAdminDiagResults__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical:
        "http://localhost:3000/educator/reports/school/diagnostic/resultsplasmic/reading/all"
    }
  }
);

export default PlasmicAdminDiagResults;
/* prettier-ignore-end */
