// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ouJBE5YY9cRiEJb3g9pqrR
// Component: KY53NiUyEo-j

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { PlasmicAdminDiagnosticResultsDataProvider } from "features/reportadmindiagnosticresults/PlasmicReportAdminDiagnosticResultsDataProvider"; // plasmic-import: nlUozUuq5AsU/codeComponent
import { HorizontalStackedBarChartWrapper } from "app/plasmic/components/ChartWrapper"; // plasmic-import: Lr5CwfIKm27J/codeComponent
import { Legend } from "common/components/presentation/Legend"; // plasmic-import: Q-IS3vQpt2kR/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ouJBE5YY9cRiEJb3g9pqrR/projectcss
import sty from "./PlasmicStudentPlacement.module.css"; // plasmic-import: KY53NiUyEo-j/css

createPlasmicElementProxy;

export type PlasmicStudentPlacement__VariantMembers = {};
export type PlasmicStudentPlacement__VariantsArgs = {};
type VariantPropType = keyof PlasmicStudentPlacement__VariantsArgs;
export const PlasmicStudentPlacement__VariantProps =
  new Array<VariantPropType>();

export type PlasmicStudentPlacement__ArgsType = {
  showLegend?: boolean;
  showComparativeView?: boolean;
};
type ArgPropType = keyof PlasmicStudentPlacement__ArgsType;
export const PlasmicStudentPlacement__ArgProps = new Array<ArgPropType>(
  "showLegend",
  "showComparativeView"
);

export type PlasmicStudentPlacement__OverridesType = {
  root?: Flex__<typeof PlasmicAdminDiagnosticResultsDataProvider>;
  freeBox?: Flex__<"div">;
  legend?: Flex__<typeof Legend>;
};

export interface DefaultStudentPlacementProps {
  showLegend?: boolean;
  showComparativeView?: boolean;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStudentPlacement__RenderFunc(props: {
  variants: PlasmicStudentPlacement__VariantsArgs;
  args: PlasmicStudentPlacement__ArgsType;
  overrides: PlasmicStudentPlacement__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          showLegend: true,
          showComparativeView: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <PlasmicAdminDiagnosticResultsDataProvider
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      previewSettings={(() => {
        try {
          return $props.showComparativeView;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return (() => {
              const __composite = { previewComparisonView: null };
              __composite["previewComparisonView"] = true;
              return __composite;
            })();
          }
          throw e;
        }
      })()}
    >
      <DataCtxReader__>
        {$ctx => (
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <HorizontalStackedBarChartWrapper
              barHeight={20}
              className={classNames(
                "__wab_instance",
                sty.horizontalStacketBarChart__rovs4
              )}
              data={(() => {
                try {
                  return $ctx.data.summary.fiveTierData.diagWindow;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [
                      {
                        category: "Not Started",
                        value: 1,
                        tooltip: "1 Student"
                      },
                      {
                        category: "In Progress",
                        value: 5,
                        tooltip: "5 Students"
                      },
                      {
                        category: "Completed",
                        value: 10,
                        tooltip: "10 Students"
                      }
                    ];
                  }
                  throw e;
                }
              })()}
              showLabels={true}
              templateName={"growthCategory6"}
            />

            {(() => {
              try {
                return $props.showComparativeView;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <HorizontalStackedBarChartWrapper
                barHeight={20}
                className={classNames(
                  "__wab_instance",
                  sty.horizontalStacketBarChart__fuYlQ
                )}
                data={(() => {
                  try {
                    return $ctx.data.summary.fiveTierData.prevWindow;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [
                        {
                          category: "Not Started",
                          value: 1,
                          tooltip: "1 Student"
                        },
                        {
                          category: "In Progress",
                          value: 5,
                          tooltip: "5 Students"
                        },
                        {
                          category: "Completed",
                          value: 10,
                          tooltip: "10 Students"
                        }
                      ];
                    }
                    throw e;
                  }
                })()}
                showLabels={true}
                templateName={"growthComparison6"}
              />
            ) : null}
            {(() => {
              try {
                return $props.showLegend;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <Legend
                data-plasmic-name={"legend"}
                data-plasmic-override={overrides.legend}
                className={classNames("__wab_instance", sty.legend)}
                data={(() => {
                  try {
                    return $ctx.data.summary.fiveLegendData;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [
                        {
                          labelText: "At Risk for Tier 3",
                          category: "17%",
                          value: 17
                        },
                        { labelText: "Tier 2", category: "20%", value: 20 },
                        { labelText: "Tier 1", category: "63%", value: 63 }
                      ];
                    }
                    throw e;
                  }
                })()}
                isAdminReport={true}
                isFiveLevel={true}
                itemWidth={"20%"}
                orientation={"horizontal"}
                templateName={"diagnosticSixThemeTemplate"}
              />
            ) : null}
          </div>
        )}
      </DataCtxReader__>
    </PlasmicAdminDiagnosticResultsDataProvider>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "legend"],
  freeBox: ["freeBox", "legend"],
  legend: ["legend"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof PlasmicAdminDiagnosticResultsDataProvider;
  freeBox: "div";
  legend: typeof Legend;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStudentPlacement__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStudentPlacement__VariantsArgs;
    args?: PlasmicStudentPlacement__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStudentPlacement__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicStudentPlacement__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStudentPlacement__ArgProps,
          internalVariantPropNames: PlasmicStudentPlacement__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStudentPlacement__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStudentPlacement";
  } else {
    func.displayName = `PlasmicStudentPlacement.${nodeName}`;
  }
  return func;
}

export const PlasmicStudentPlacement = Object.assign(
  // Top-level PlasmicStudentPlacement renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    legend: makeNodeComponent("legend"),

    // Metadata about props expected for PlasmicStudentPlacement
    internalVariantProps: PlasmicStudentPlacement__VariantProps,
    internalArgProps: PlasmicStudentPlacement__ArgProps
  }
);

export default PlasmicStudentPlacement;
/* prettier-ignore-end */
