// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ouJBE5YY9cRiEJb3g9pqrR
// Component: L_F0JU74xLD_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { PlasmicAdminDiagnosticResultsDataProvider } from "features/reportadmindiagnosticresults/PlasmicReportAdminDiagnosticResultsDataProvider"; // plasmic-import: nlUozUuq5AsU/codeComponent
import { CollapsibleDrawerWrapper } from "app/plasmic/components/CollapsibleDrawerWrapper"; // plasmic-import: xtWRylWrNUH4/codeComponent
import { HorizontalStackedBarChartWrapper } from "app/plasmic/components/ChartWrapper"; // plasmic-import: Lr5CwfIKm27J/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ouJBE5YY9cRiEJb3g9pqrR/projectcss
import sty from "./PlasmicPlacementByDomainDrawer.module.css"; // plasmic-import: L_F0JU74xLD_/css

createPlasmicElementProxy;

export type PlasmicPlacementByDomainDrawer__VariantMembers = {};
export type PlasmicPlacementByDomainDrawer__VariantsArgs = {};
type VariantPropType = keyof PlasmicPlacementByDomainDrawer__VariantsArgs;
export const PlasmicPlacementByDomainDrawer__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPlacementByDomainDrawer__ArgsType = {
  openOnInit?: boolean;
  domainData?: any;
};
type ArgPropType = keyof PlasmicPlacementByDomainDrawer__ArgsType;
export const PlasmicPlacementByDomainDrawer__ArgProps = new Array<ArgPropType>(
  "openOnInit",
  "domainData"
);

export type PlasmicPlacementByDomainDrawer__OverridesType = {
  root?: Flex__<typeof PlasmicAdminDiagnosticResultsDataProvider>;
  collapseDrawer?: Flex__<typeof CollapsibleDrawerWrapper>;
  columns?: Flex__<"div">;
  text?: Flex__<"div">;
};

export interface DefaultPlacementByDomainDrawerProps {
  openOnInit?: boolean;
  domainData?: any;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPlacementByDomainDrawer__RenderFunc(props: {
  variants: PlasmicPlacementByDomainDrawer__VariantsArgs;
  args: PlasmicPlacementByDomainDrawer__ArgsType;
  overrides: PlasmicPlacementByDomainDrawer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          openOnInit: false,
          domainData: [
            {
              values: [
                { category: "Category 1", tooltip: "31%", value: 31 },
                { category: "Category 2", tooltip: "1%", value: 1 },
                { category: "Category 3", tooltip: "2%", value: 2 },
                { category: "Category 4", tooltip: "1%", value: 1 },
                { category: "Category 5", tooltip: "25%", value: 25 },
                { category: "Category 6", tooltip: "40%", value: 40 }
              ],
              label: "PA",
              name: "Phonological Awareness",
              prevValues: [
                { category: "Category 1", tooltip: null, value: null },
                { category: "Category 2", tooltip: null, value: null },
                { category: "Category 3", tooltip: null, value: null },
                { category: "Category 4", tooltip: null, value: null },
                { category: "Category 5", tooltip: null, value: null },
                { category: "Category 6", tooltip: null, value: null }
              ]
            },
            {
              values: [
                { category: "Category 1", tooltip: "40%", value: 40 },
                { category: "Category 2", tooltip: "0%", value: 0 },
                { category: "Category 3", tooltip: "5%", value: 5 },
                { category: "Category 4", tooltip: "2%", value: 2 },
                { category: "Category 5", tooltip: "53%", value: 53 },
                { category: "Category 6", tooltip: "0%", value: 0 }
              ],
              label: "PH",
              name: "Phonics",
              prevValues: [
                { category: "Category 1", tooltip: null, value: null },
                { category: "Category 2", tooltip: null, value: null },
                { category: "Category 3", tooltip: null, value: null },
                { category: "Category 4", tooltip: null, value: null },
                { category: "Category 5", tooltip: null, value: null },
                { category: "Category 6", tooltip: null, value: null }
              ]
            },
            {
              values: [
                { category: "Category 1", tooltip: "60%", value: 60 },
                { category: "Category 2", tooltip: "0%", value: 0 },
                { category: "Category 3", tooltip: "3%", value: 3 },
                { category: "Category 4", tooltip: "1%", value: 1 },
                { category: "Category 5", tooltip: "35%", value: 35 },
                { category: "Category 6", tooltip: "1%", value: 1 }
              ],
              label: "HFW",
              name: "High-Frequency Words",
              prevValues: [
                { category: "Category 1", tooltip: null, value: null },
                { category: "Category 2", tooltip: null, value: null },
                { category: "Category 3", tooltip: null, value: null },
                { category: "Category 4", tooltip: null, value: null },
                { category: "Category 5", tooltip: null, value: null },
                { category: "Category 6", tooltip: null, value: null }
              ]
            },
            {
              values: [
                { category: "Category 1", tooltip: "21%", value: 21 },
                { category: "Category 2", tooltip: "9%", value: 9 },
                { category: "Category 3", tooltip: "14%", value: 14 },
                { category: "Category 4", tooltip: "5%", value: 5 },
                { category: "Category 5", tooltip: "51%", value: 51 },
                { category: "Category 6", tooltip: "0%", value: 0 }
              ],
              label: "VOC",
              name: "Vocabulary",
              prevValues: [
                { category: "Category 1", tooltip: null, value: null },
                { category: "Category 2", tooltip: null, value: null },
                { category: "Category 3", tooltip: null, value: null },
                { category: "Category 4", tooltip: null, value: null },
                { category: "Category 5", tooltip: null, value: null },
                { category: "Category 6", tooltip: null, value: null }
              ]
            },
            {
              values: [
                { category: "Category 1", tooltip: "22%", value: 22 },
                { category: "Category 2", tooltip: "7%", value: 7 },
                { category: "Category 3", tooltip: "14%", value: 14 },
                { category: "Category 4", tooltip: "5%", value: 5 },
                { category: "Category 5", tooltip: "52%", value: 52 },
                { category: "Category 6", tooltip: "0%", value: 0 }
              ],
              label: "LIT",
              name: "Comprehension: Literature",
              prevValues: [
                { category: "Category 1", tooltip: null, value: null },
                { category: "Category 2", tooltip: null, value: null },
                { category: "Category 3", tooltip: null, value: null },
                { category: "Category 4", tooltip: null, value: null },
                { category: "Category 5", tooltip: null, value: null },
                { category: "Category 6", tooltip: null, value: null }
              ]
            },
            {
              values: [
                { category: "Category 1", tooltip: "21%", value: 21 },
                { category: "Category 2", tooltip: "10%", value: 10 },
                { category: "Category 3", tooltip: "12%", value: 12 },
                { category: "Category 4", tooltip: "5%", value: 5 },
                { category: "Category 5", tooltip: "52%", value: 52 },
                { category: "Category 6", tooltip: "0%", value: 0 }
              ],
              label: "INFO",
              name: "Comprehension: Informational Text",
              prevValues: [
                { category: "Category 1", tooltip: null, value: null },
                { category: "Category 2", tooltip: null, value: null },
                { category: "Category 3", tooltip: null, value: null },
                { category: "Category 4", tooltip: null, value: null },
                { category: "Category 5", tooltip: null, value: null },
                { category: "Category 6", tooltip: null, value: null }
              ]
            }
          ]
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <PlasmicAdminDiagnosticResultsDataProvider
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <DataCtxReader__>
        {$ctx => (
          <CollapsibleDrawerWrapper
            data-plasmic-name={"collapseDrawer"}
            data-plasmic-override={overrides.collapseDrawer}
            cardVariant={"grey_v3"}
            className={classNames("__wab_instance", sty.collapseDrawer)}
            clickableTitle={true}
            closeIcon={"card-arrow-open"}
            disableScrollIntoView={true}
            openIcon={"card-arrow-closed"}
            openOnInit={true}
            title={"Placement by Domain"}
          >
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $props.domainData;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <div
                  data-plasmic-name={"columns"}
                  data-plasmic-override={overrides.columns}
                  className={classNames(projectcss.all, sty.columns)}
                  key={currentIndex}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__ye6Pw)}
                  >
                    <div
                      data-plasmic-name={"text"}
                      data-plasmic-override={overrides.text}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return currentItem.name;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__kSlJz)}
                  >
                    <HorizontalStackedBarChartWrapper
                      barHeight={12}
                      className={classNames(
                        "__wab_instance",
                        sty.horizontalStacketBarChart__kisFe
                      )}
                      data={(() => {
                        try {
                          return currentItem.values;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [
                              {
                                category: "Not Started",
                                value: 1,
                                tooltip: "1 Student"
                              },
                              {
                                category: "In Progress",
                                value: 5,
                                tooltip: "5 Students"
                              },
                              {
                                category: "Completed",
                                value: 10,
                                tooltip: "10 Students"
                              }
                            ];
                          }
                          throw e;
                        }
                      })()}
                      templateName={"growthCategory6"}
                    />

                    {(() => {
                      try {
                        return $ctx.data.isPreviousWindowSelected;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return true;
                        }
                        throw e;
                      }
                    })() ? (
                      <HorizontalStackedBarChartWrapper
                        barHeight={12}
                        className={classNames(
                          "__wab_instance",
                          sty.horizontalStacketBarChart___1ROp
                        )}
                        data={(() => {
                          try {
                            return currentItem.prevValues;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return [
                                {
                                  category: "Not Started",
                                  value: 1,
                                  tooltip: "1 Student"
                                },
                                {
                                  category: "In Progress",
                                  value: 5,
                                  tooltip: "5 Students"
                                },
                                {
                                  category: "Completed",
                                  value: 10,
                                  tooltip: "10 Students"
                                }
                              ];
                            }
                            throw e;
                          }
                        })()}
                        templateName={"growthComparison6"}
                      />
                    ) : null}
                  </div>
                </div>
              );
            })}
          </CollapsibleDrawerWrapper>
        )}
      </DataCtxReader__>
    </PlasmicAdminDiagnosticResultsDataProvider>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "collapseDrawer", "columns", "text"],
  collapseDrawer: ["collapseDrawer", "columns", "text"],
  columns: ["columns", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof PlasmicAdminDiagnosticResultsDataProvider;
  collapseDrawer: typeof CollapsibleDrawerWrapper;
  columns: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPlacementByDomainDrawer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPlacementByDomainDrawer__VariantsArgs;
    args?: PlasmicPlacementByDomainDrawer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPlacementByDomainDrawer__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPlacementByDomainDrawer__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPlacementByDomainDrawer__ArgProps,
          internalVariantPropNames: PlasmicPlacementByDomainDrawer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPlacementByDomainDrawer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPlacementByDomainDrawer";
  } else {
    func.displayName = `PlasmicPlacementByDomainDrawer.${nodeName}`;
  }
  return func;
}

export const PlasmicPlacementByDomainDrawer = Object.assign(
  // Top-level PlasmicPlacementByDomainDrawer renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    collapseDrawer: makeNodeComponent("collapseDrawer"),
    columns: makeNodeComponent("columns"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicPlacementByDomainDrawer
    internalVariantProps: PlasmicPlacementByDomainDrawer__VariantProps,
    internalArgProps: PlasmicPlacementByDomainDrawer__ArgProps
  }
);

export default PlasmicPlacementByDomainDrawer;
/* prettier-ignore-end */
