// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ouJBE5YY9cRiEJb3g9pqrR
// Component: FBn8CS733jVG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { PlasmicAdminDiagnosticResultsDataProvider } from "features/reportadmindiagnosticresults/PlasmicReportAdminDiagnosticResultsDataProvider"; // plasmic-import: nlUozUuq5AsU/codeComponent
import { CustomTabs } from "app/plasmic/components/CustomTabsWrapper"; // plasmic-import: WenUTxKTZeKN/codeComponent
import ThreeTierPlacement from "../../ThreeTierPlacement"; // plasmic-import: ZvHkj5qtG8Mt/component
import { PlacementByDomain } from "features/reportadmindiagnosticresults/diagnosticresults/threeleveltab/PlacementByDomain"; // plasmic-import: jVQkLOSj3VZi/codeComponent
import { PlasmicAdminDiagnosticResultsTableDataProvider } from "features/reportadmindiagnosticresults/PlasmicReportAdminDiagnosticResultsTableDataProvider"; // plasmic-import: b945fY3JqbSH/codeComponent
import { CustomTableWrapper } from "app/plasmic/components/CustomTableWrapper"; // plasmic-import: c1JGwLPYCVD-/codeComponent
import StudentPlacementChart from "../../StudentPlacementChart"; // plasmic-import: PXRdsVnjPbUQ/component
import { FiveLevelPlacementsPopover } from "features/reportadmindiagnosticresults/diagnosticresults/fiveleveltab/FiveLevelPlacementsPopover"; // plasmic-import: R4EaJyhzI-rx/codeComponent
import PlacementByDomainDrawer from "../../PlacementByDomainDrawer"; // plasmic-import: L_F0JU74xLD_/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ouJBE5YY9cRiEJb3g9pqrR/projectcss
import sty from "./PlasmicAdminDiagResultsReportContent.module.css"; // plasmic-import: FBn8CS733jVG/css

createPlasmicElementProxy;

export type PlasmicAdminDiagResultsReportContent__VariantMembers = {};
export type PlasmicAdminDiagResultsReportContent__VariantsArgs = {};
type VariantPropType = keyof PlasmicAdminDiagResultsReportContent__VariantsArgs;
export const PlasmicAdminDiagResultsReportContent__VariantProps =
  new Array<VariantPropType>();

export type PlasmicAdminDiagResultsReportContent__ArgsType = {};
type ArgPropType = keyof PlasmicAdminDiagResultsReportContent__ArgsType;
export const PlasmicAdminDiagResultsReportContent__ArgProps =
  new Array<ArgPropType>();

export type PlasmicAdminDiagResultsReportContent__OverridesType = {
  root?: Flex__<typeof PlasmicAdminDiagnosticResultsDataProvider>;
  tabs?: Flex__<typeof CustomTabs>;
  _3LevelTab?: Flex__<"section">;
  studentsAssessedTotal?: Flex__<"div">;
  columns?: Flex__<"div">;
  threeTierPlacement?: Flex__<typeof ThreeTierPlacement>;
  placementByDomain?: Flex__<typeof PlacementByDomain>;
  _5LevelTab?: Flex__<"section">;
  studentsAssessedTotal2?: Flex__<"div">;
  studentPlacementChart?: Flex__<typeof StudentPlacementChart>;
  placementsPopover?: Flex__<typeof FiveLevelPlacementsPopover>;
  freTab?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultAdminDiagResultsReportContentProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAdminDiagResultsReportContent__RenderFunc(props: {
  variants: PlasmicAdminDiagResultsReportContent__VariantsArgs;
  args: PlasmicAdminDiagResultsReportContent__ArgsType;
  overrides: PlasmicAdminDiagResultsReportContent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <PlasmicAdminDiagnosticResultsDataProvider
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      previewSettings={(() => {
        const __composite = { previewComparisonView: null };
        __composite["previewComparisonView"] = false;
        return __composite;
      })()}
    >
      <DataCtxReader__>
        {$ctx => (
          <CustomTabs
            data-plasmic-name={"tabs"}
            data-plasmic-override={overrides.tabs}
            activeTab={1}
            className={classNames("__wab_instance", sty.tabs)}
            tabList={(() => {
              const __composite = [
                {
                  tabName: "3-Level Placement",
                  tabValue: "THREE_LEVEL_PLACEMENTS"
                },
                {
                  tabName: "5-Level Placement",
                  tabValue: "FIVE_LEVEL_PLACEMENTS",
                  badgeText: null
                },
                {
                  tabName: "Foundational Reading Extension",
                  tabValue: "FOUNDATIONAL_READING"
                },
                {
                  tabName: "Projected Proficiency",
                  tabValue: "PROJECTED_PROFICIENCY"
                }
              ];
              __composite["1"]["badgeText"] = "Enhanced";
              return __composite;
            })()}
            variant={"arrows"}
          >
            <section
              data-plasmic-name={"_3LevelTab"}
              data-plasmic-override={overrides._3LevelTab}
              className={classNames(projectcss.all, sty._3LevelTab)}
            >
              <div className={classNames(projectcss.all, sty.column__pAnrV)}>
                <div
                  data-plasmic-name={"studentsAssessedTotal"}
                  data-plasmic-override={overrides.studentsAssessedTotal}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.studentsAssessedTotal
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return `Students Assessed/Total: ${$ctx.data.summary.assessedStudentCount}/${$ctx.data.summary.totalStudentCount}`;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Students Assessed/ Total: ";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l3Ohf
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ textDecorationLine: "underline" }}
                    >
                      {"Criterion Referenced"}
                    </span>
                  </React.Fragment>
                </div>
                <div
                  data-plasmic-name={"columns"}
                  data-plasmic-override={overrides.columns}
                  className={classNames(projectcss.all, sty.columns)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__r1E95)}
                  >
                    <ThreeTierPlacement
                      data-plasmic-name={"threeTierPlacement"}
                      data-plasmic-override={overrides.threeTierPlacement}
                      className={classNames(
                        "__wab_instance",
                        sty.threeTierPlacement
                      )}
                    />
                  </div>
                  <div className={classNames(projectcss.all, sty.column__dZVy)}>
                    <PlacementByDomain
                      data-plasmic-name={"placementByDomain"}
                      data-plasmic-override={overrides.placementByDomain}
                      className={classNames(
                        "__wab_instance",
                        sty.placementByDomain
                      )}
                      isComparativeView={(() => {
                        try {
                          return $ctx.data.isPreviousWindowSelected;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return false;
                          }
                          throw e;
                        }
                      })()}
                      placementsByDomain={(() => {
                        try {
                          return $ctx.data.summary.threeTier.placementsByDomain;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return {
                              domain1: {
                                name: "Domain A",
                                label: "D1",
                                values: {
                                  currentWindow: [
                                    { category: "Not Started", value: 1 },
                                    { category: "In Progress", value: 2 },
                                    { category: "Completed", value: 3 }
                                  ],
                                  previousWindow: [
                                    { category: "Not Started", value: 1 },
                                    { category: "In Progress", value: 2 },
                                    { category: "Completed", value: 3 }
                                  ]
                                }
                              },
                              domain2: {
                                name: "Domain 2",
                                label: "D2",
                                values: {
                                  currentWindow: [
                                    { category: "Not Started", value: 1 },
                                    { category: "In Progress", value: 2 },
                                    { category: "Completed", value: 3 }
                                  ],
                                  previousWindow: [
                                    { category: "Not Started", value: 1 },
                                    { category: "In Progress", value: 2 },
                                    { category: "Completed", value: 3 }
                                  ]
                                }
                              }
                            };
                          }
                          throw e;
                        }
                      })()}
                    />
                  </div>
                </div>
                <PlasmicAdminDiagnosticResultsTableDataProvider
                  className={classNames(
                    "__wab_instance",
                    sty.adminDiagnosticResultsTableDataProvider___8Xs9Q
                  )}
                >
                  <DataCtxReader__>
                    {$ctx => (
                      <CustomTableWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.table___8FaZq
                        )}
                        columns={(() => {
                          const __composite = [
                            { type: null, width: null },
                            { type: null, title: null },
                            { title: null, width: null, dataIndex: null }
                          ];
                          __composite["0"]["type"] = "population";
                          __composite["0"]["width"] = "20%";
                          __composite["1"]["type"] = "three-level-tiers";
                          __composite["1"]["title"] =
                            "Overall Grade-Level Placement";
                          __composite["2"]["title"] = "Students Assessed/Total";
                          __composite["2"]["width"] = "13%";
                          __composite["2"]["dataIndex"] =
                            "studentsAssessedTotal";
                          return __composite;
                        })()}
                        dataSource={(() => {
                          try {
                            return $ctx.data.tableData;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return {};
                            }
                            throw e;
                          }
                        })()}
                      />
                    )}
                  </DataCtxReader__>
                </PlasmicAdminDiagnosticResultsTableDataProvider>
              </div>
            </section>
            <section
              data-plasmic-name={"_5LevelTab"}
              data-plasmic-override={overrides._5LevelTab}
              className={classNames(projectcss.all, sty._5LevelTab)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___90TJ
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ textDecorationLine: "underline" }}
                  >
                    {"Criteria Referenced"}
                  </span>
                </React.Fragment>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lm6L0
                )}
              >
                {"Overall Placement"}
              </div>
              <div
                data-plasmic-name={"studentsAssessedTotal2"}
                data-plasmic-override={overrides.studentsAssessedTotal2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.studentsAssessedTotal2
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return `Students Assessed/Total: ${$ctx.data.summary.assessedStudentCount}/${$ctx.data.summary.totalStudentCount}`;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "Students Assessed/ Total: ";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
              <StudentPlacementChart
                data-plasmic-name={"studentPlacementChart"}
                data-plasmic-override={overrides.studentPlacementChart}
                className={classNames(
                  "__wab_instance",
                  sty.studentPlacementChart
                )}
              />

              <FiveLevelPlacementsPopover
                data-plasmic-name={"placementsPopover"}
                data-plasmic-override={overrides.placementsPopover}
                className={classNames("__wab_instance", sty.placementsPopover)}
              />

              <PlacementByDomainDrawer
                className={classNames(
                  "__wab_instance",
                  sty.placementByDomainDrawer__g71Zt
                )}
                domainData={(() => {
                  try {
                    return $ctx.data.summary.fiveTierPlacementWindow1;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [
                        {
                          values: [
                            {
                              category: "Category 1",
                              tooltip: "31%",
                              value: 31
                            },
                            { category: "Category 2", tooltip: "1%", value: 1 },
                            { category: "Category 3", tooltip: "2%", value: 2 },
                            { category: "Category 4", tooltip: "1%", value: 1 },
                            {
                              category: "Category 5",
                              tooltip: "25%",
                              value: 25
                            },
                            {
                              category: "Category 6",
                              tooltip: "40%",
                              value: 40
                            }
                          ],
                          label: "PA",
                          name: "Phonological Awareness",
                          prevValues: [
                            {
                              category: "Category 1",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 2",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 3",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 4",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 5",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 6",
                              tooltip: null,
                              value: null
                            }
                          ]
                        },
                        {
                          values: [
                            {
                              category: "Category 1",
                              tooltip: "40%",
                              value: 40
                            },
                            { category: "Category 2", tooltip: "0%", value: 0 },
                            { category: "Category 3", tooltip: "5%", value: 5 },
                            { category: "Category 4", tooltip: "2%", value: 2 },
                            {
                              category: "Category 5",
                              tooltip: "53%",
                              value: 53
                            },
                            { category: "Category 6", tooltip: "0%", value: 0 }
                          ],
                          label: "PH",
                          name: "Phonics",
                          prevValues: [
                            {
                              category: "Category 1",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 2",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 3",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 4",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 5",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 6",
                              tooltip: null,
                              value: null
                            }
                          ]
                        },
                        {
                          values: [
                            {
                              category: "Category 1",
                              tooltip: "60%",
                              value: 60
                            },
                            { category: "Category 2", tooltip: "0%", value: 0 },
                            { category: "Category 3", tooltip: "3%", value: 3 },
                            { category: "Category 4", tooltip: "1%", value: 1 },
                            {
                              category: "Category 5",
                              tooltip: "35%",
                              value: 35
                            },
                            { category: "Category 6", tooltip: "1%", value: 1 }
                          ],
                          label: "HFW",
                          name: "High-Frequency Words",
                          prevValues: [
                            {
                              category: "Category 1",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 2",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 3",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 4",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 5",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 6",
                              tooltip: null,
                              value: null
                            }
                          ]
                        },
                        {
                          values: [
                            {
                              category: "Category 1",
                              tooltip: "21%",
                              value: 21
                            },
                            { category: "Category 2", tooltip: "9%", value: 9 },
                            {
                              category: "Category 3",
                              tooltip: "14%",
                              value: 14
                            },
                            { category: "Category 4", tooltip: "5%", value: 5 },
                            {
                              category: "Category 5",
                              tooltip: "51%",
                              value: 51
                            },
                            { category: "Category 6", tooltip: "0%", value: 0 }
                          ],
                          label: "VOC",
                          name: "Vocabulary",
                          prevValues: [
                            {
                              category: "Category 1",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 2",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 3",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 4",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 5",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 6",
                              tooltip: null,
                              value: null
                            }
                          ]
                        },
                        {
                          values: [
                            {
                              category: "Category 1",
                              tooltip: "22%",
                              value: 22
                            },
                            { category: "Category 2", tooltip: "7%", value: 7 },
                            {
                              category: "Category 3",
                              tooltip: "14%",
                              value: 14
                            },
                            { category: "Category 4", tooltip: "5%", value: 5 },
                            {
                              category: "Category 5",
                              tooltip: "52%",
                              value: 52
                            },
                            { category: "Category 6", tooltip: "0%", value: 0 }
                          ],
                          label: "LIT",
                          name: "Comprehension: Literature",
                          prevValues: [
                            {
                              category: "Category 1",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 2",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 3",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 4",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 5",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 6",
                              tooltip: null,
                              value: null
                            }
                          ]
                        },
                        {
                          values: [
                            {
                              category: "Category 1",
                              tooltip: "21%",
                              value: 21
                            },
                            {
                              category: "Category 2",
                              tooltip: "10%",
                              value: 10
                            },
                            {
                              category: "Category 3",
                              tooltip: "12%",
                              value: 12
                            },
                            { category: "Category 4", tooltip: "5%", value: 5 },
                            {
                              category: "Category 5",
                              tooltip: "52%",
                              value: 52
                            },
                            { category: "Category 6", tooltip: "0%", value: 0 }
                          ],
                          label: "INFO",
                          name: "Comprehension: Informational Text",
                          prevValues: [
                            {
                              category: "Category 1",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 2",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 3",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 4",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 5",
                              tooltip: null,
                              value: null
                            },
                            {
                              category: "Category 6",
                              tooltip: null,
                              value: null
                            }
                          ]
                        }
                      ];
                    }
                    throw e;
                  }
                })()}
                openOnInit={true}
              />

              <PlasmicAdminDiagnosticResultsTableDataProvider
                className={classNames(
                  "__wab_instance",
                  sty.adminDiagnosticResultsTableDataProvider__lbYBp
                )}
              >
                <DataCtxReader__>
                  {$ctx => (
                    <CustomTableWrapper
                      className={classNames("__wab_instance", sty.table__qjyH2)}
                      columns={(() => {
                        const __composite = [
                          { type: null, width: null },
                          { type: null },
                          { type: null, iconOnly: null },
                          { title: null, width: null, dataIndex: null }
                        ];
                        __composite["0"]["type"] = "population";
                        __composite["0"]["width"] = "20%";
                        __composite["1"]["type"] = "tiers";
                        __composite["2"]["type"] = "fiveLevelPercentages";
                        __composite["2"]["iconOnly"] = true;
                        __composite["3"]["title"] = "Students Assessed/Total";
                        __composite["3"]["width"] = "13%";
                        __composite["3"]["dataIndex"] = "studentsAssessedTotal";
                        return __composite;
                      })()}
                      dataSource={(() => {
                        try {
                          return $ctx.data.tableData;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return {};
                          }
                          throw e;
                        }
                      })()}
                    />
                  )}
                </DataCtxReader__>
              </PlasmicAdminDiagnosticResultsTableDataProvider>
            </section>
            <div
              data-plasmic-name={"freTab"}
              data-plasmic-override={overrides.freTab}
              className={classNames(projectcss.all, sty.freTab)}
            >
              <div className={classNames(projectcss.all, sty.column__jq2K9)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d2MZk
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "This tab includes data from the foundational reading domains.\n\nSome students who originally Surpassed Level or were Not Assessed in these domains may have been given additional questions due to district requirements. Those results and results from students who were not given additional questions are presented together here. Foundational reading domain results here may be different than results shown on the 5-Level Placement tab; however, additional results shown here do not impact Overall Scores or Overall Placements.\n\nLearn more about the "
                      }
                    </React.Fragment>
                    {
                      <PlasmicLink__
                        data-plasmic-name={"link"}
                        data-plasmic-override={overrides.link}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link
                        )}
                        component={Link}
                        href={
                          "https://i-readycentral.com/download/?res=115762&view_pdf=1"
                        }
                        platform={"nextjs"}
                      >
                        {"Foundational Reading Extension here."}
                      </PlasmicLink__>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cqlCv
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ textDecorationLine: "underline" }}
                    >
                      {"Criterion Referenced"}
                    </span>
                  </React.Fragment>
                </div>
                <PlacementByDomainDrawer
                  className={classNames(
                    "__wab_instance",
                    sty.placementByDomainDrawer__wzlDk
                  )}
                  domainData={(() => {
                    try {
                      return $ctx.data.summary.placementByDomainFREWindow1;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [
                          {
                            values: [
                              {
                                category: "Category 1",
                                tooltip: "31%",
                                value: 31
                              },
                              {
                                category: "Category 2",
                                tooltip: "1%",
                                value: 1
                              },
                              {
                                category: "Category 3",
                                tooltip: "2%",
                                value: 2
                              },
                              {
                                category: "Category 4",
                                tooltip: "1%",
                                value: 1
                              },
                              {
                                category: "Category 5",
                                tooltip: "25%",
                                value: 25
                              },
                              {
                                category: "Category 6",
                                tooltip: "40%",
                                value: 40
                              }
                            ],
                            label: "PA",
                            name: "Phonological Awareness",
                            prevValues: [
                              {
                                category: "Category 1",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 2",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 3",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 4",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 5",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 6",
                                tooltip: null,
                                value: null
                              }
                            ]
                          },
                          {
                            values: [
                              {
                                category: "Category 1",
                                tooltip: "40%",
                                value: 40
                              },
                              {
                                category: "Category 2",
                                tooltip: "0%",
                                value: 0
                              },
                              {
                                category: "Category 3",
                                tooltip: "5%",
                                value: 5
                              },
                              {
                                category: "Category 4",
                                tooltip: "2%",
                                value: 2
                              },
                              {
                                category: "Category 5",
                                tooltip: "53%",
                                value: 53
                              },
                              {
                                category: "Category 6",
                                tooltip: "0%",
                                value: 0
                              }
                            ],
                            label: "PH",
                            name: "Phonics",
                            prevValues: [
                              {
                                category: "Category 1",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 2",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 3",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 4",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 5",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 6",
                                tooltip: null,
                                value: null
                              }
                            ]
                          },
                          {
                            values: [
                              {
                                category: "Category 1",
                                tooltip: "60%",
                                value: 60
                              },
                              {
                                category: "Category 2",
                                tooltip: "0%",
                                value: 0
                              },
                              {
                                category: "Category 3",
                                tooltip: "3%",
                                value: 3
                              },
                              {
                                category: "Category 4",
                                tooltip: "1%",
                                value: 1
                              },
                              {
                                category: "Category 5",
                                tooltip: "35%",
                                value: 35
                              },
                              {
                                category: "Category 6",
                                tooltip: "1%",
                                value: 1
                              }
                            ],
                            label: "HFW",
                            name: "High-Frequency Words",
                            prevValues: [
                              {
                                category: "Category 1",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 2",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 3",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 4",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 5",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 6",
                                tooltip: null,
                                value: null
                              }
                            ]
                          },
                          {
                            values: [
                              {
                                category: "Category 1",
                                tooltip: "21%",
                                value: 21
                              },
                              {
                                category: "Category 2",
                                tooltip: "9%",
                                value: 9
                              },
                              {
                                category: "Category 3",
                                tooltip: "14%",
                                value: 14
                              },
                              {
                                category: "Category 4",
                                tooltip: "5%",
                                value: 5
                              },
                              {
                                category: "Category 5",
                                tooltip: "51%",
                                value: 51
                              },
                              {
                                category: "Category 6",
                                tooltip: "0%",
                                value: 0
                              }
                            ],
                            label: "VOC",
                            name: "Vocabulary",
                            prevValues: [
                              {
                                category: "Category 1",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 2",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 3",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 4",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 5",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 6",
                                tooltip: null,
                                value: null
                              }
                            ]
                          },
                          {
                            values: [
                              {
                                category: "Category 1",
                                tooltip: "22%",
                                value: 22
                              },
                              {
                                category: "Category 2",
                                tooltip: "7%",
                                value: 7
                              },
                              {
                                category: "Category 3",
                                tooltip: "14%",
                                value: 14
                              },
                              {
                                category: "Category 4",
                                tooltip: "5%",
                                value: 5
                              },
                              {
                                category: "Category 5",
                                tooltip: "52%",
                                value: 52
                              },
                              {
                                category: "Category 6",
                                tooltip: "0%",
                                value: 0
                              }
                            ],
                            label: "LIT",
                            name: "Comprehension: Literature",
                            prevValues: [
                              {
                                category: "Category 1",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 2",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 3",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 4",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 5",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 6",
                                tooltip: null,
                                value: null
                              }
                            ]
                          },
                          {
                            values: [
                              {
                                category: "Category 1",
                                tooltip: "21%",
                                value: 21
                              },
                              {
                                category: "Category 2",
                                tooltip: "10%",
                                value: 10
                              },
                              {
                                category: "Category 3",
                                tooltip: "12%",
                                value: 12
                              },
                              {
                                category: "Category 4",
                                tooltip: "5%",
                                value: 5
                              },
                              {
                                category: "Category 5",
                                tooltip: "52%",
                                value: 52
                              },
                              {
                                category: "Category 6",
                                tooltip: "0%",
                                value: 0
                              }
                            ],
                            label: "INFO",
                            name: "Comprehension: Informational Text",
                            prevValues: [
                              {
                                category: "Category 1",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 2",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 3",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 4",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 5",
                                tooltip: null,
                                value: null
                              },
                              {
                                category: "Category 6",
                                tooltip: null,
                                value: null
                              }
                            ]
                          }
                        ];
                      }
                      throw e;
                    }
                  })()}
                />
              </div>
            </div>
          </CustomTabs>
        )}
      </DataCtxReader__>
    </PlasmicAdminDiagnosticResultsDataProvider>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "tabs",
    "_3LevelTab",
    "studentsAssessedTotal",
    "columns",
    "threeTierPlacement",
    "placementByDomain",
    "_5LevelTab",
    "studentsAssessedTotal2",
    "studentPlacementChart",
    "placementsPopover",
    "freTab",
    "link"
  ],
  tabs: [
    "tabs",
    "_3LevelTab",
    "studentsAssessedTotal",
    "columns",
    "threeTierPlacement",
    "placementByDomain",
    "_5LevelTab",
    "studentsAssessedTotal2",
    "studentPlacementChart",
    "placementsPopover",
    "freTab",
    "link"
  ],
  _3LevelTab: [
    "_3LevelTab",
    "studentsAssessedTotal",
    "columns",
    "threeTierPlacement",
    "placementByDomain"
  ],
  studentsAssessedTotal: ["studentsAssessedTotal"],
  columns: ["columns", "threeTierPlacement", "placementByDomain"],
  threeTierPlacement: ["threeTierPlacement"],
  placementByDomain: ["placementByDomain"],
  _5LevelTab: [
    "_5LevelTab",
    "studentsAssessedTotal2",
    "studentPlacementChart",
    "placementsPopover"
  ],
  studentsAssessedTotal2: ["studentsAssessedTotal2"],
  studentPlacementChart: ["studentPlacementChart"],
  placementsPopover: ["placementsPopover"],
  freTab: ["freTab", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof PlasmicAdminDiagnosticResultsDataProvider;
  tabs: typeof CustomTabs;
  _3LevelTab: "section";
  studentsAssessedTotal: "div";
  columns: "div";
  threeTierPlacement: typeof ThreeTierPlacement;
  placementByDomain: typeof PlacementByDomain;
  _5LevelTab: "section";
  studentsAssessedTotal2: "div";
  studentPlacementChart: typeof StudentPlacementChart;
  placementsPopover: typeof FiveLevelPlacementsPopover;
  freTab: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAdminDiagResultsReportContent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAdminDiagResultsReportContent__VariantsArgs;
    args?: PlasmicAdminDiagResultsReportContent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    PlasmicAdminDiagResultsReportContent__VariantsArgs,
    ReservedPropsType
  > &
    /* Specify args directly as props*/ Omit<
      PlasmicAdminDiagResultsReportContent__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAdminDiagResultsReportContent__ArgProps,
          internalVariantPropNames:
            PlasmicAdminDiagResultsReportContent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAdminDiagResultsReportContent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAdminDiagResultsReportContent";
  } else {
    func.displayName = `PlasmicAdminDiagResultsReportContent.${nodeName}`;
  }
  return func;
}

export const PlasmicAdminDiagResultsReportContent = Object.assign(
  // Top-level PlasmicAdminDiagResultsReportContent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tabs: makeNodeComponent("tabs"),
    _3LevelTab: makeNodeComponent("_3LevelTab"),
    studentsAssessedTotal: makeNodeComponent("studentsAssessedTotal"),
    columns: makeNodeComponent("columns"),
    threeTierPlacement: makeNodeComponent("threeTierPlacement"),
    placementByDomain: makeNodeComponent("placementByDomain"),
    _5LevelTab: makeNodeComponent("_5LevelTab"),
    studentsAssessedTotal2: makeNodeComponent("studentsAssessedTotal2"),
    studentPlacementChart: makeNodeComponent("studentPlacementChart"),
    placementsPopover: makeNodeComponent("placementsPopover"),
    freTab: makeNodeComponent("freTab"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicAdminDiagResultsReportContent
    internalVariantProps: PlasmicAdminDiagResultsReportContent__VariantProps,
    internalArgProps: PlasmicAdminDiagResultsReportContent__ArgProps
  }
);

export default PlasmicAdminDiagResultsReportContent;
/* prettier-ignore-end */
